# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/will/.local/share/scripts/qtpad/gui_style.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(440, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(440, 180))
        Dialog.setMaximumSize(QtCore.QSize(440, 180))
        Dialog.setModal(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.widthOpt = QtWidgets.QSpinBox(Dialog)
        self.widthOpt.setMaximum(9999)
        self.widthOpt.setObjectName("widthOpt")
        self.gridLayout.addWidget(self.widthOpt, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.backgroundOpt = QtWidgets.QToolButton(Dialog)
        self.backgroundOpt.setObjectName("backgroundOpt")
        self.gridLayout.addWidget(self.backgroundOpt, 0, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.heightOpt = QtWidgets.QSpinBox(Dialog)
        self.heightOpt.setMaximum(9999)
        self.heightOpt.setObjectName("heightOpt")
        self.gridLayout.addWidget(self.heightOpt, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.fontcolorOpt = QtWidgets.QToolButton(Dialog)
        self.fontcolorOpt.setObjectName("fontcolorOpt")
        self.gridLayout.addWidget(self.fontcolorOpt, 1, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.fontsizeOpt = QtWidgets.QSpinBox(Dialog)
        self.fontsizeOpt.setObjectName("fontsizeOpt")
        self.gridLayout.addWidget(self.fontsizeOpt, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 3, 1, 1)
        self.fontfamilyOpt = QtWidgets.QFontComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontfamilyOpt.sizePolicy().hasHeightForWidth())
        self.fontfamilyOpt.setSizePolicy(sizePolicy)
        self.fontfamilyOpt.setMaximumSize(QtCore.QSize(150, 16777215))
        self.fontfamilyOpt.setObjectName("fontfamilyOpt")
        self.gridLayout.addWidget(self.fontfamilyOpt, 2, 4, 1, 3)
        self.backgroundLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backgroundLabel.sizePolicy().hasHeightForWidth())
        self.backgroundLabel.setSizePolicy(sizePolicy)
        self.backgroundLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.gridLayout.addWidget(self.backgroundLabel, 0, 4, 1, 1)
        self.fontcolorLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontcolorLabel.sizePolicy().hasHeightForWidth())
        self.fontcolorLabel.setSizePolicy(sizePolicy)
        self.fontcolorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fontcolorLabel.setObjectName("fontcolorLabel")
        self.gridLayout.addWidget(self.fontcolorLabel, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Default appearance"))
        self.label.setText(_translate("Dialog", "Width"))
        self.label_3.setText(_translate("Dialog", "Background color"))
        self.backgroundOpt.setText(_translate("Dialog", "..."))
        self.label_2.setText(_translate("Dialog", "Height"))
        self.label_4.setText(_translate("Dialog", "Font color"))
        self.fontcolorOpt.setText(_translate("Dialog", "..."))
        self.label_5.setText(_translate("Dialog", "Font size"))
        self.label_6.setText(_translate("Dialog", "Font family"))
        self.backgroundLabel.setText(_translate("Dialog", "#ffffff"))
        self.fontcolorLabel.setText(_translate("Dialog", "#ffffff"))

